services:
  db:
    image: postgres:15-alpine
    container_name: lisa_db
    restart: always
    environment:
      POSTGRES_USER: ${LISA_DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${LISA_DB_PASSWORD:-password}
      POSTGRES_DB: ${LISA_DB_NAME:-backend_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${LISA_DB_USERNAME:-user} -d ${LISA_DB_NAME:-backend_db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
