# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/${LISA_DB_NAME:backend_db}
spring.datasource.username=${LISA_DB_USERNAME:user}
spring.datasource.password=${LISA_DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true