DROP TABLE IF EXISTS test_entity;

CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  product_type_id BIGINT NOT NULL,
  brand_id BIGINT,
  unit_id BIGINT NOT NULL,
  parent_product_id BIGINT,
  name VARCHAR(255),
  description TEXT,
  base_quantity DECIMAL(16,6),
  extra_free_quantity DECIMAL(16,6),
  gtin VARCHAR(14) UNIQUE,
  deposit DECIMAL(12,2),
  is_abstract_product BOOLEAN NOT NULL DEFAULT false,


  CONSTRAINT chk_name_length CHECK (LENGTH(name) >= 3 AND LENGTH(name) <= 255),
  CONSTRAINT chk_positive_base CHECK (base_quantity > 0),
  CONSTRAINT chk_positive_free CHECK (extra_free_quantity > 0),
  CONSTRAINT chk_positive_deposit CHECK (deposit > 0),
  CONSTRAINT chk_gtin_numeric CHECK (gtin ~ '^[0-9]+$'),
  CONSTRAINT chk_gtin_length CHECK (LENGTH(gtin) >= 8 AND LENGTH(gtin) <= 14),
  CONSTRAINT chk_no_gtin_if_abstract CHECK (NOT (gtin IS NOT NULL AND is_abstract_product = TRUE)),
  CONSTRAINT chk_product_not_own_parent CHECK (id <> parent_product_id)
);

CREATE INDEX idx_product_type_id ON product(product_type_id);
CREATE INDEX idx_product_brand_id ON product(brand_id);
CREATE INDEX idx_product_unit_id ON product(unit_id);
CREATE INDEX idx_product_parent_product_id ON product(parent_product_id);


CREATE TABLE brand (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  name VARCHAR(50) UNIQUE NOT NULL,
  is_private_label BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT chk_brand_name_length CHECK (LENGTH(name) >= 2 AND LENGTH(name) <= 50)
);


CREATE TABLE product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  parent_product_category_id BIGINT,

  CONSTRAINT chk_category_not_own_parent CHECK (id <> parent_product_category_id),
  CONSTRAINT chk_category_name_length CHECK(LENGTH(name) >= 3 AND LENGTH(name) <= 255)
);

CREATE INDEX idx_product_category_parent_id ON product_category(parent_product_category_id);


CREATE TABLE product_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  product_category_id BIGINT NOT NULL,

  CONSTRAINT chk_type_name_length CHECK(LENGTH(name) >= 3 AND LENGTH(name) <= 100)
);

CREATE INDEX idx_product_type_category_id ON product_type(product_category_id);


CREATE TABLE unit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_type VARCHAR(10) NOT NULL,
  comparison_factor INTEGER NOT NULL,

  CONSTRAINT chk_positive_comparison_factor CHECK (comparison_factor > 0 AND comparison_factor <= 9999)
);

CREATE UNIQUE INDEX uq_unit_type_comparison_factor ON unit (unit_type, comparison_factor);


COMMENT ON TABLE product_category IS 'Hierarchische Kategorisierung von Produkten, z.B. Milchprodukte, Getränke, Obst & Gemüse etc.';

COMMENT ON TABLE product_type IS 'Definiert die Substitutionsklasse. Produkte innerhalb eines Typs sind für den Endnutzer funktional austauschbar (z.B. Frischmilch vs. Frischmilch).';

COMMENT ON COLUMN product.brand_id IS 'NULL bei markenlosen Produkten (z.B. loses Gemüse)';
COMMENT ON COLUMN product.parent_product_id IS 'NULL = Basis-Produkt / NOT NULL = Konkrete Sorte/Größe';
COMMENT ON COLUMN product.name IS 'z.B. Classic, Zero, Cherry';
COMMENT ON COLUMN product.base_quantity IS 'Die reguläre Menge, z.B. 450 (g)';
COMMENT ON COLUMN product.extra_free_quantity IS 'Der Gratis-Zusatz, z.B. 50 (g)';
COMMENT ON COLUMN product.gtin IS 'Global Trade Item Number ist eine Identifikationsnummer, mit der Produkte und Packstücke weltweit eindeutig identifiziert werden können. Kann führende Nullen enthalten.';
COMMENT ON COLUMN product.deposit IS 'Pfandwert pro Einheit (z.B. 0,25€)';
COMMENT ON COLUMN product.is_abstract_product IS 'Abstraktes Produkt ja/nein? Abstrakte Produkte können nicht gekauft werden, nur dessen Child-Produkte';

COMMENT ON COLUMN brand.is_private_label IS 'Eigenmarke?';

COMMENT ON COLUMN unit.unit_type IS 'technischer Enum String für kg, l, Stück etc.';
COMMENT ON COLUMN unit.comparison_factor IS 'Faktor des Verhältnisses auf die Basiseinheit, z.B. 100 für 100 Stück zu Stück';


ALTER TABLE product ADD FOREIGN KEY (parent_product_id) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product ADD FOREIGN KEY (product_type_id) REFERENCES product_type (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product ADD FOREIGN KEY (brand_id) REFERENCES brand (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE product ADD FOREIGN KEY (unit_id) REFERENCES unit (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_category ADD FOREIGN KEY (parent_product_category_id) REFERENCES product_category (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_type ADD FOREIGN KEY (product_category_id) REFERENCES product_category (id) DEFERRABLE INITIALLY IMMEDIATE;