CREATE SCHEMA IF NOT EXISTS availability;


CREATE TABLE availability.product_listing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  product_uuid UUID NOT NULL,
  retailer_id BIGINT NOT NULL,
  sku VARCHAR(16),
  current_price_uuid UUID, -- Optionaler Pointer
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ,
  
  CONSTRAINT chk_cronological_dates CHECK (start_at <= end_at),
  CONSTRAINT chk_sku_length CHECK (LENGTH(sku) >= 8 AND LENGTH(sku) <= 16)
);

CREATE INDEX idx_product_listing_product_uuid ON availability.product_listing(product_uuid);
CREATE INDEX idx_product_listing_retailer_id ON availability.product_listing(retailer_id);
CREATE UNIQUE INDEX uq_active_product_listing ON availability.product_listing(product_uuid, retailer_id) WHERE (end_at IS NULL);

CREATE TABLE availability.retailer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  name VARCHAR(50) UNIQUE NOT NULL,
  
  CONSTRAINT chk_retailer_name_length CHECK (LENGTH(name) >= 2 AND LENGTH(name) <= 50)
);

CREATE TABLE availability.retailer_brand_listing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retailer_id BIGINT NOT NULL,
  brand_uuid UUID NOT NULL,
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ,
  
  CONSTRAINT chk_cronological_dates CHECK (start_at <= end_at)
);

CREATE INDEX idx_retailer_brand_listing_retailer_id ON availability.retailer_brand_listing(retailer_id);
CREATE INDEX idx_retailer_brand_listing_brand_uuid ON availability.retailer_brand_listing(brand_uuid);
CREATE UNIQUE INDEX uq_active_brand_listing ON availability.retailer_brand_listing(retailer_id, brand_uuid) WHERE (end_at IS NULL);


COMMENT ON COLUMN availability.product_listing.sku IS 'Händlerspezifische Artikelnummer';
COMMENT ON COLUMN availability.product_listing.current_price_uuid IS 'Performance Pointer auf den aktuellen Preis dieses Händlers';


ALTER TABLE availability.product_listing ADD FOREIGN KEY (retailer_id) REFERENCES availability.retailer (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE availability.retailer_brand_listing ADD FOREIGN KEY (retailer_id) REFERENCES availability.retailer (id) DEFERRABLE INITIALLY IMMEDIATE;
