CREATE SCHEMA IF NOT EXISTS pricing;

CREATE TABLE pricing.price (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  product_listing_uuid UUID NOT NULL,
  price_type VARCHAR(20) NOT NULL,
  value_per_base_unit DECIMAL(16,6) NOT NULL,
  value_per_package DECIMAL(16,6), -- verhindert Rundungsfehler beim Erstellen von PurchaseItems
  is_redeemed BOOLEAN NOT NULL DEFAULT false,
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ,

  CONSTRAINT chk_positive_price CHECK (value_per_base_unit >= 0),
  CONSTRAINT chk_positive_price_per_package CHECK (value_per_package >= 0),
  CONSTRAINT chk_cronological_dates CHECK (start_at <= end_at),
  CONSTRAINT chk_only_standard_unlimited CHECK ((price_type = 'STANDARD') OR (end_at IS NOT NULL))
);

CREATE INDEX idx_price_product_listing_uuid ON pricing.price(product_listing_uuid);
CREATE INDEX idx_price_type ON pricing.price(price_type);
CREATE UNIQUE INDEX uq_price_type_start ON pricing.price (product_listing_uuid, price_type, start_at);
CREATE UNIQUE INDEX uq_price_no_end ON pricing.price (product_listing_uuid, price_type) WHERE (end_at IS NULL AND is_redeemed = FALSE);


COMMENT ON COLUMN pricing.price.value_per_package IS 'Der tatsächliche Preis der Packung am Regal, insofern nicht kontinuierlich messbar wie Bananen';