CREATE SCHEMA IF NOT EXISTS sales;

CREATE TABLE sales.purchase (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  retailer_uuid UUID NOT NULL,
  purchase_at TIMESTAMPTZ NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  total_deposit_buy DECIMAL(12,2),
  total_deposit_return DECIMAL(12,2),
  basket_discount_amount DECIMAL(12,2),
  redeemed_credit DECIMAL(12,2),
  total_sum DECIMAL(12,2) NOT NULL,

  CONSTRAINT chk_positive_deposit_buy CHECK (total_deposit_buy > 0),
  CONSTRAINT chk_positive_deposit_return CHECK (total_deposit_return > 0),
  CONSTRAINT chk_positive_basket_discount CHECK (basket_discount_amount > 0),
  CONSTRAINT chk_positive_redeemed_credit CHECK (redeemed_credit > 0),
  CONSTRAINT chk_purchase_total_consistency CHECK (total_sum = subtotal - COALESCE(basket_discount_amount, 0) + COALESCE(total_deposit_buy, 0) - COALESCE(total_deposit_return, 0) - COALESCE(redeemed_credit, 0))
);

CREATE INDEX idx_purchase_retailer_uuid ON sales.purchase(retailer_uuid);
CREATE INDEX idx_purchase_purchase_at ON sales.purchase(purchase_at);

CREATE TABLE sales.line_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id BIGINT NOT NULL,
  product_listing_uuid UUID NOT NULL,
  quantity DECIMAL(12,4) NOT NULL,
  price_at_purchase DECIMAL(12,2) NOT NULL,
  discount_amount DECIMAL(12,2),
  total_deposit DECIMAL(12,2),
  total_line_price DECIMAL(12,2) NOT NULL,

  CONSTRAINT chk_item_positive_quantity CHECK (quantity > 0),
  CONSTRAINT chk_item_positive_price CHECK (price_at_purchase >= 0),
  CONSTRAINT chk_item_positive_discount CHECK (discount_amount > 0),
  CONSTRAINT chk_item_positive_deposit CHECK (total_deposit > 0),
  CONSTRAINT chk_discount_not_exceeding_value CHECK (price_at_purchase >= COALESCE(discount_amount, 0)),
  CONSTRAINT chk_line_price_consistency CHECK (total_line_price = (quantity * price_at_purchase) - COALESCE(discount_amount, 0)),
  CONSTRAINT chk_item_positive_line_price CHECK (total_line_price > 0),
  CONSTRAINT fk_line_item_purchase FOREIGN KEY (purchase_id) REFERENCES sales.purchase (id) ON DELETE CASCADE
);

CREATE INDEX idx_purchase_item_purchase_id ON sales.line_item(purchase_id);
CREATE INDEX idx_purchase_item_product_listing_uuid ON sales.line_item(product_listing_uuid);


COMMENT ON COLUMN sales.purchase.subtotal IS 'Summe aller Artikelpreise vor Warenkorb-Rabatt';
COMMENT ON COLUMN sales.purchase.total_deposit_buy IS 'Summierter Pfandwert der gekauften Artikel';
COMMENT ON COLUMN sales.purchase.total_deposit_return IS 'Summierter Pfandwert der abgegebenen Artikel';
COMMENT ON COLUMN sales.purchase.basket_discount_amount IS 'z.B. 10% Coupon auf den ganzen Einkauf in absoluten Zahlen. Senkt Warenwert';
COMMENT ON COLUMN sales.purchase.redeemed_credit IS 'Eingelöster Guthabenbetrag, z.B. von Bonus-Aktionen oder einem Kundenkonto. Senkt Zahlungsbetrag';
COMMENT ON COLUMN sales.purchase.total_sum IS 'endgültiger Zahlungsbetrag';

COMMENT ON COLUMN sales.line_item.quantity IS 'Anzahl der Artikel, bspw. 250g Bananen oder 3 mal 1 Stück Milch á 1l';
COMMENT ON COLUMN sales.line_item.price_at_purchase IS 'Regal-/Apppreis zum Zeitpunkt des Kaufs, verrechnet mit der quantity';
COMMENT ON COLUMN sales.line_item.discount_amount IS 'z.B. -30% Frischerabatt in absoluten Zahlen';
COMMENT ON COLUMN sales.line_item.total_deposit IS 'Gesamtpfandwert für die Artikelmenge';
COMMENT ON COLUMN sales.line_item.total_line_price IS 'Gesamtpreis der Zeile aus Stückpreis, Menge und abzüglich möglicher Rabatte';


ALTER TABLE sales.line_item ADD FOREIGN KEY (purchase_id) REFERENCES sales.purchase (id) DEFERRABLE INITIALLY IMMEDIATE;